name: Build macOS App with GUI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pyinstaller

      - name: Build Mac App with PyInstaller
        run: |
          pyinstaller --onefile --windowed add_gst_to_item_master.py --add-data "GST-Rates.xlsx:."

      - name: Upload App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gst_enricher_macos
          path: dist/*
          if-no-files-found: warn
